name: geoenv
channels:
  - conda-forge
dependencies:
  - python=3.11  # 3.11 is recommended for maximum GIS wheel/Conda stability
  # GIS Core
  - geopandas
  - rasterio
  - rasterstats
  - rioxarray
  - xarray
  - shapely
  - dask
  # Data Manipulation & Analysis
  - pandas
  - numpy
  # Jupyter / Interactive Support
  - ipykernel
