# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-03-14 17:05:33
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
def #  NOT  IMPLEMENTED# Function Body not implemented

def MBUpdateJLThesisImpSurfaces():  # MBUpdate_JLThesis_ImpSurfaces

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Maddie\Dropbox (ASU)\Donovan_Lab_GIS\Drivers\2_Urban_Runoff\Urban_Scratch.gdb", workspace=r"C:\Users\Maddie\Dropbox (ASU)\Donovan_Lab_GIS\Drivers\2_Urban_Runoff\Urban_Scratch.gdb"):
        shoreline_OTP_editForEucDist = "C:\\Workspace\\CumulativeImpacts\\Stressors\\LBSP\\Runoff_Proxies\\Geodatabase\\InputData.gdb\\shoreline_OTP_editForEucDist"
        WBD_HU12_n83utm_merge_clean = "C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\0_Input_Data_and_Models\\Common_Inputs_2022\\Common_2022-23.gdb\\WBD_HU12_n83utm_merge_clean"
        WBD_HU12_n84utm5N_merge_clean = "WBD_HU12_n84utm5N_merge_clean"
        Int_HI_South = arcpy.Raster("Int_HI_South")
        OceanMask_100m_2023_10 = arcpy.Raster("C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\0_Input_Data_and_Models\\Common_Inputs_2022\\Common_2022-23.gdb\\OceanMask_100m_2023_10")
        DistFromShore_Euc_2023 = arcpy.Raster("C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\0_Input_Data_and_Models\\Common_Inputs_2022\\Common_2022-23.gdb\\DistFromShore_Euc_2023")
        Imperv_Dissolve_Area17 = "Imperv_Dissolve_Area17"
        tiled = "C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\2_Urban_Runoff\\LARGE-input-data\\CCAP2017_impsurfaces\\tiled"
        hi_south_piece7_reclass = arcpy.Raster("C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\2_Urban_Runoff\\Urban_Scratch.gdb\\hi_south_piece7_reclass")
        Tabulat_WBD_HU11 = "Tabulat_WBD_HU11"

        for Tiles, Name in #  NOT  IMPLEMENTED(tiled, "", "TIF", "NOT_RECURSIVE"):

            # Process: Raster Calculator (Raster Calculator) (sa)
            tile_reclass = "C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\2_Urban_Runoff\\Urban_Scratch.gdb\\tile_reclass"
            Raster_Calculator = tile_reclass
            tile_reclass = Con(Int_HI_South == 1, 1)
            tile_reclass.save(Raster_Calculator)


            # Process: Tabulate Area (Tabulate Area) (sa)
            Imperv_byWatershed = "C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\2_Urban_Runoff\\Urban_Scratch.gdb\\Imperv_byWatershed"
            arcpy.sa.TabulateArea(in_zone_data=WBD_HU12_n84utm5N_merge_clean, zone_field="HUC12", in_class_data=tile_reclass, class_field="Value", out_table=Imperv_byWatershed, processing_cell_size="C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\2_Urban_Runoff\\Urban_Scratch.gdb\\hi_south_piece7_reclass", classes_as_rows="CLASSES_AS_FIELDS")
            .save(Tabulate_Area)


            # Process: Add Field (Add Field) (management)
            Imperv_byWatershed_New_Field = arcpy.management.AddField(in_table=Imperv_byWatershed, field_name="Imperv_2017_numeric", field_type="LONG", field_precision=None, field_scale=None, field_length=None, field_alias="Area Impervious 2017 Numeric", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

            # Process: Calculate Field (Calculate Field) (management)
            Imperv_byWatershed_Numeric = arcpy.management.CalculateField(in_table=Imperv_byWatershed_New_Field, field="Imperv_2017_numeric", expression="!VALUE_1!", expression_type="PYTHON3", code_block="", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

            # Process: Join Field (Join Field) (management)
            WBD_HU12_n83utm_merge_clean_2_ = arcpy.management.JoinField(in_data=WBD_HU12_n83utm_merge_clean, in_field="HUC12", join_table=Imperv_byWatershed_Numeric, join_field="HUC12", fields=["Imperv_2017_numeric"], fm_option="NOT_USE_FM", field_mapping="")[0]

            # Process: Calculate Field (3) (Calculate Field) (management)
            WBD_HU12_n83utm_merge_clean_3_ = arcpy.management.CalculateField(in_table=WBD_HU12_n83utm_merge_clean_2_, field="Imperv_2017_numeric_1", expression="replaceNull(!Imperv_2017_numeric_1!)", expression_type="PYTHON3", code_block="""def replaceNull(val):
    if val is None:
        return 0
    else:
        return val""", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

            # Process: Polygon to Raster (2) (Polygon to Raster) (conversion)
            Imperv_byWatershed_ras_100m17 = "C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\2_Urban_Runoff\\Urban_Scratch.gdb\\Imperv_byWatershed_ras_100m17"
            with arcpy.EnvManager(snapRaster=OceanMask_100m_2023_10):
                arcpy.conversion.PolygonToRaster(in_features=WBD_HU12_n83utm_merge_clean_3_, value_field="Imperv_2017_numeric_1", out_rasterdataset=Imperv_byWatershed_ras_100m17, cell_assignment="MAXIMUM_AREA", priority_field="Imperv_2017_numeric_1", cellsize=OceanMask_100m_2023_10, build_rat="DO_NOT_BUILD")

            # Process: Focal Statistics (Focal Statistics) (sa)
            Imperv_FocStMean_2km = "C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\2_Urban_Runoff\\Urban_Scratch.gdb\\Imperv_FocStMean_2km"
            Focal_Statistics = Imperv_FocStMean_2km
            with arcpy.EnvManager(extent=OceanMask_100m_2023_10, snapRaster=OceanMask_100m_2023_10):
                Imperv_FocStMean_2km = arcpy.sa.FocalStatistics(in_raster=Imperv_byWatershed_ras_100m17, neighborhood="Circle 21 CELL", statistics_type="MEAN", ignore_nodata="DATA", percentile_value=90)
                Imperv_FocStMean_2km.save(Focal_Statistics)


            # Process: Extract by Mask (Extract by Mask) (sa)
            Imperv_FocStMean_2km_Ext = "C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\2_Urban_Runoff\\Urban_Scratch.gdb\\Imperv_FocStMean_2km_Ext"
            Extract_by_Mask = Imperv_FocStMean_2km_Ext
            with arcpy.EnvManager(extent=OceanMask_100m_2023_10, snapRaster=OceanMask_100m_2023_10):
                Imperv_FocStMean_2km_Ext = arcpy.sa.ExtractByMask(in_raster=Imperv_FocStMean_2km, in_mask_data=OceanMask_100m_2023_10, extraction_area="INSIDE", analysis_extent="340124.48858642 2089230.66607933 945324.48858642 2464030.66607933 PROJCS[\"NAD_1983_UTM_Zone_4N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-159.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")
                Imperv_FocStMean_2km_Ext.save(Extract_by_Mask)


            # Process: Raster Calculator (2) (Raster Calculator) (sa)
            Imperv_MeanDecay_2017 = "C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\2_Urban_Runoff\\Urban_Scratch.gdb\\Imperv_MeanDecay_2017"
            Raster_Calculator_2_ = Imperv_MeanDecay_2017
            Imperv_MeanDecay_2017 = Imperv_FocStMean_2km_Ext * Exp( -1 * ((DistFromShore_Euc_2023 ** 2.5) / 10 ** 7.5))
            Imperv_MeanDecay_2017.save(Raster_Calculator_2_)


            # Process: Get Raster Properties (Get Raster Properties) (management)
            Property = arcpy.management.GetRasterProperties(in_raster=Imperv_MeanDecay_2017, property_type="MAXIMUM", band_index="")[0]

            # Process: Raster Calculator (3) (Raster Calculator) (sa)
            Imperv_MeanDecay_01_2017 = "C:\\Users\\Maddie\\Dropbox (ASU)\\Donovan_Lab_GIS\\Drivers\\2_Urban_Runoff\\Urban_Scratch.gdb\\Imperv_MeanDecay_01_2017"
            Raster_Calculator_3_ = Imperv_MeanDecay_01_2017
            if Property:
                Imperv_MeanDecay_01_2017 =  Float("%Imperv_MeanDecay%") / 1603507.25
                Imperv_MeanDecay_01_2017.save(Raster_Calculator_3_)


if __name__ == '__main__':
    MBUpdateJLThesisImpSurfaces()
